---
- hosts: vagrant
  sudo: true
  vars:
    hostname: vagrant-ansible-rails
    environtment: vagrant
    ruby_version: 2.2.2
    rbenv_root: /home/vagrant/.rbenv
    rbenv_bin: /home/vagrant/.rbenv/libexec/rbenv
    group: ops
    user: ops
  roles:
    - common
    - mysql
    - deploy_user
