default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: urban_outdoor_development
test:
  <<: *default
  database: urban_outdoor_test
production:
  <<: *default
  database: urban_outdoor_production
  username: urban_outdoor
  password: <%= ENV['URBAN_OUTDOOR_DATABASE_PASSWORD'] %>
